GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "Learn NodeJS"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "todo": "Rafi Putra Ramadhan"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 0
}